# Frases simples por grupo de classe terapêutica da lista CMED/Anvisa.
# Texto geral, de demonstração: precisa de revisão de farmacêutico.
# Formato: código -> (apelido, para que serve, cuidado extra ou "")
# Regras por palavra da classe (REGRAS) têm prioridade sobre o código.

G = {
 'A1':  ('remédio para a boca', 'Trata problemas na boca, como feridas e infecções.', ''),
 'A10': ('remédio do açúcar no sangue', 'Ajuda a controlar o açúcar no sangue, no diabetes.', 'Não pule refeições. Se sentir tremor, suor frio ou fraqueza, coma algo doce e chame alguém.'),
 'A11': ('vitamina', 'Repõe vitaminas que estão faltando no corpo.', ''),
 'A12': ('suplemento mineral', 'Repõe minerais como cálcio ou potássio.', ''),
 'A13': ('tônico', 'Usado como fortificante.', ''),
 'A14': ('hormônio anabolizante', 'Hormônio usado em casos específicos indicados pelo médico.', 'Use só com acompanhamento médico.'),
 'A15': ('remédio para o apetite', 'Ajuda a abrir o apetite.', ''),
 'A16': ('remédio para a digestão', 'Usado em problemas do aparelho digestivo.', ''),
 'A2':  ('remédio do estômago', 'Protege o estômago e diminui a acidez, a azia e a gastrite.', ''),
 'A3':  ('remédio para cólica e estômago', 'Alivia cólicas e ajuda o estômago a funcionar melhor.', ''),
 'A4':  ('remédio para enjoo', 'Diminui enjoo e vômito.', ''),
 'A5':  ('remédio do fígado e da vesícula', 'Usado em problemas do fígado e da vesícula.', ''),
 'A6':  ('laxante', 'Ajuda o intestino preso a funcionar.', 'Não use por muito tempo sem falar com o médico.'),
 'A7':  ('remédio para diarreia e intestino', 'Usado na diarreia e em problemas do intestino.', 'Beba bastante água.'),
 'A8':  ('remédio para emagrecer', 'Usado no tratamento da obesidade.', ''),
 'A9':  ('remédio para a digestão', 'Ajuda a digerir os alimentos.', ''),
 'B1':  ('remédio para afinar o sangue', 'Ajuda a evitar coágulos e entupimento das veias.', 'Pode causar sangramento. Avise o médico se aparecerem manchas roxas, sangue na urina ou nas fezes.'),
 'B2':  ('remédio da coagulação do sangue', 'Ajuda o sangue a coagular e controla sangramentos.', ''),
 'B3':  ('remédio para anemia', 'Trata a anemia, repondo ferro ou ajudando o sangue.', ''),
 'B6':  ('remédio para o sangue', 'Usado em problemas específicos do sangue.', ''),
 'C1':  ('remédio do coração', 'Ajuda o coração a funcionar e controla o ritmo dos batimentos.', 'Não pare de uma vez. Fale antes com o médico.'),
 'C10': ('remédio do colesterol', 'Baixa o colesterol e a gordura no sangue e protege o coração.', 'Avise o médico se sentir dor forte nos músculos.'),
 'C11': ('remédio do colesterol', 'Baixa o colesterol e a gordura no sangue.', ''),
 'C2':  ('remédio da pressão', 'Controla a pressão alta.', 'Levante devagar se sentir tontura.'),
 'C3':  ('remédio que faz urinar', 'Tira o excesso de água do corpo e ajuda a baixar a pressão.', 'Faz ir mais vezes ao banheiro. Costuma ser tomado de manhã.'),
 'C4':  ('remédio para a circulação', 'Ajuda a circulação do sangue.', ''),
 'C5':  ('remédio para varizes e hemorroidas', 'Ajuda a circulação das veias, em varizes e hemorroidas.', ''),
 'C6':  ('remédio da pressão', 'Usado no controle da pressão.', ''),
 'C7':  ('remédio da pressão e do coração', 'Baixa a pressão e deixa o coração bater mais calmo.', 'Nunca pare de uma vez. Fale antes com o médico.'),
 'C8':  ('remédio da pressão', 'Relaxa os vasos do sangue e baixa a pressão.', 'Pode inchar um pouco os tornozelos. Se acontecer, avise o médico.'),
 'C9':  ('remédio da pressão', 'Controla a pressão alta e protege o coração e os rins.', 'Levante devagar se sentir tontura.'),
 'D1':  ('pomada para micose', 'Trata micose e frieira na pele.', 'Use na pele. Não engula.'),
 'D10': ('remédio para espinhas', 'Trata acne e espinhas.', ''),
 'D11': ('produto para a pele', 'Usado em problemas da pele.', 'Use só na pele.'),
 'D2':  ('creme hidratante', 'Hidrata e protege a pele.', 'Use só na pele.'),
 'D3':  ('produto para feridas', 'Ajuda a cicatrizar feridas na pele.', 'Use só na pele.'),
 'D4':  ('remédio para coceira', 'Alivia a coceira na pele.', 'Use só na pele.'),
 'D5':  ('remédio para psoríase e pele', 'Trata psoríase e inflamações da pele.', ''),
 'D6':  ('pomada para infecção de pele', 'Trata infecções na pele.', 'Use só na pele.'),
 'D7':  ('pomada de corticoide', 'Diminui inflamação, vermelhidão e coceira na pele.', 'Use só na pele e pelo tempo que o médico mandou.'),
 'D8':  ('antisséptico', 'Limpa e desinfeta a pele e pequenos machucados.', 'Uso externo. Não engula.'),
 'G03': ('hormônio', 'Hormônio usado conforme orientação médica.', ''),
 'G04': ('remédio da bexiga', 'Usado em problemas urinários.', ''),
 'G1':  ('remédio ginecológico', 'Trata infecções e corrimentos íntimos.', ''),
 'G2':  ('remédio ginecológico', 'Usado em tratamentos ginecológicos.', ''),
 'G3':  ('anticoncepcional ou hormônio feminino', 'Evita a gravidez ou repõe hormônios femininos.', 'Tome sempre no mesmo horário.'),
 'G4':  ('remédio da bexiga e da próstata', 'Usado em problemas urinários, de próstata ou de ereção.', ''),
 'H1':  ('hormônio', 'Hormônio usado em tratamentos específicos.', 'Use só com acompanhamento médico.'),
 'H2':  ('corticoide', 'Diminui inflamações e alergias fortes.', 'Não pare de uma vez se usar por muitos dias. Fale com o médico.'),
 'H3':  ('remédio da tireoide', 'Controla a tireoide.', 'Costuma ser tomado em jejum, de manhã.'),
 'H4':  ('hormônio', 'Hormônio usado em tratamentos específicos.', 'Use só com acompanhamento médico.'),
 'J05': ('remédio para hepatite', 'Trata hepatite causada por vírus.', ''),
 'J07': ('vacina', 'Protege contra doenças.', ''),
 'J1':  ('antibiótico', 'Combate infecções causadas por bactérias.', 'Tome todos os dias, no horário certo, até o fim do tratamento, mesmo se melhorar antes.'),
 'J2':  ('remédio para micose', 'Trata infecções causadas por fungos.', 'Tome até o fim do tratamento.'),
 'J3':  ('antibiótico', 'Combate infecções causadas por bactérias.', 'Tome até o fim do tratamento.'),
 'J4':  ('remédio para tuberculose ou hanseníase', 'Trata tuberculose ou hanseníase.', 'Não pare o tratamento. Ele é longo e precisa ir até o fim.'),
 'J5':  ('antiviral', 'Combate infecções causadas por vírus.', 'Tome no horário certo, sem pular doses.'),
 'J6':  ('imunoglobulina ou soro', 'Ajuda a defesa do corpo.', 'Aplicado por profissional de saúde.'),
 'J7':  ('vacina', 'Protege contra doenças.', ''),
 'J8':  ('remédio para infecção', 'Combate infecções.', 'Tome até o fim do tratamento.'),
 'K1':  ('soro', 'Solução usada no soro, em hospital ou posto.', 'Aplicado por profissional de saúde.'),
 'K2':  ('solução hospitalar', 'Usada em hospital.', 'Aplicado por profissional de saúde.'),
 'K3':  ('solução hospitalar', 'Usada em hospital.', 'Aplicado por profissional de saúde.'),
 'K4':  ('solução hospitalar', 'Usada em hospital.', 'Aplicado por profissional de saúde.'),
 'K5':  ('solução de lavagem', 'Usada em procedimentos de saúde.', ''),
 'K6':  ('solução para diálise', 'Usada na diálise.', ''),
 'L01': ('remédio para câncer', 'Usado no tratamento do câncer.', 'Use só com acompanhamento do médico especialista.'),
 'L1':  ('remédio para câncer', 'Usado no tratamento do câncer.', 'Use só com acompanhamento do médico especialista.'),
 'L2':  ('remédio para câncer', 'Usado no tratamento do câncer.', 'Use só com acompanhamento do médico especialista.'),
 'L3':  ('remédio para a imunidade', 'Ajuda a defesa do corpo.', 'Use só com acompanhamento médico.'),
 'L4':  ('remédio para a imunidade', 'Controla a defesa do corpo, em doenças como artrite e em transplantes.', 'Use só com acompanhamento médico. Avise se tiver febre.'),
 'M1':  ('remédio para dor e inflamação', 'Alivia dor, inchaço e inflamação nas juntas e nos músculos.', 'Tome depois de comer. Pode fazer mal ao estômago.'),
 'M2':  ('pomada para dor', 'Alivia dor nos músculos e nas juntas.', 'Use só na pele.'),
 'M3':  ('relaxante muscular', 'Relaxa os músculos e alivia contraturas.', 'Pode dar sono.'),
 'M4':  ('remédio para gota', 'Trata a gota e baixa o ácido úrico.', 'Beba bastante água.'),
 'M5':  ('remédio para os ossos', 'Fortalece os ossos, na osteoporose.', ''),
 'N1':  ('anestésico', 'Tira a dor para procedimentos.', 'Aplicado por profissional de saúde.'),
 'N2':  ('remédio para dor', 'Alivia dor e febre.', 'Não tome mais do que o recomendado.'),
 'N3':  ('remédio para convulsão', 'Previne convulsões. Também é usado em algumas dores e no humor.', 'Nunca pare de uma vez. Pode dar sono.'),
 'N4':  ('remédio para Parkinson', 'Ajuda a controlar os tremores e os movimentos.', 'Tome sempre nos mesmos horários.'),
 'N5':  ('remédio para os nervos', 'Usado para acalmar, dormir ou tratar problemas da mente.', 'Pode dar sono. Não pare de uma vez e não misture com bebida alcoólica.'),
 'N6':  ('remédio para depressão e ansiedade', 'Ajuda a melhorar o humor e a ansiedade.', 'O efeito pode demorar algumas semanas. Não pare de uma vez.'),
 'N7':  ('remédio para memória e tontura', 'Usado em problemas da memória, tontura e outros do sistema nervoso.', ''),
 'P1':  ('remédio para vermes e parasitas', 'Trata vermes e outros parasitas.', ''),
 'P3':  ('remédio para piolho e sarna', 'Trata piolho e sarna.', 'Uso externo.'),
 'R03': ('remédio da asma', 'Ajuda a respirar melhor, na asma e na bronquite.', ''),
 'R1':  ('remédio para o nariz', 'Desentope e trata o nariz.', 'Não use descongestionante por mais de poucos dias.'),
 'R2':  ('remédio para a garganta', 'Alivia dor e irritação na garganta.', ''),
 'R3':  ('remédio da asma', 'Ajuda a respirar melhor, na asma e na bronquite.', 'Leve sempre a bombinha de alívio.'),
 'R4':  ('pomada para respirar', 'Ajuda a respirar melhor no resfriado.', 'Uso externo.'),
 'R5':  ('remédio para tosse e gripe', 'Alivia tosse, catarro e sintomas da gripe.', ''),
 'R6':  ('antialérgico', 'Alivia alergia, coceira e espirros.', 'Pode dar sono.'),
 'R7':  ('remédio para o pulmão', 'Usado em doenças do pulmão.', ''),
 'S1':  ('colírio ou remédio dos olhos', 'Trata problemas nos olhos.', 'Use só nos olhos.'),
 'S2':  ('remédio para o ouvido', 'Trata problemas no ouvido.', 'Use só no ouvido.'),
 'S3':  ('remédio para olhos e ouvidos', 'Trata problemas nos olhos ou no ouvido.', ''),
 'T1':  ('contraste para exame', 'Usado em exames de imagem.', 'Aplicado por profissional de saúde.'),
 'T2':  ('produto para exame', 'Usado em exames.', ''),
 'V07': ('produto de saúde', 'Usado em tratamentos de saúde.', ''),
 'V3':  ('remédio de uso especial', 'Usado em tratamentos específicos.', 'Use só com acompanhamento médico.'),
 'FITO':('remédio de planta', 'Remédio feito de plantas.', ''),
}

# palavra na classe -> grupo de frase (tem prioridade)
REGRAS = [
 ('ANALGÉSICOS NARCÓTICOS', 'N2X', ('remédio forte para dor', 'Alivia dores fortes.', 'Pode dar sono e prisão de ventre. Não misture com bebida alcoólica.')),
 ('GABAPENTIN', 'N2G', ('remédio para dor nos nervos', 'Alivia dor nos nervos e formigamento.', 'Pode dar sono e tontura.')),
 ('HIPNÓTICOS', 'N5H', ('remédio para dormir', 'Ajuda a dormir.', 'Pode dar sono no dia seguinte. Cuidado para não cair. Não misture com bebida alcoólica.')),
 ('TRANQUILIZANTES', 'N5T', ('calmante', 'Acalma e diminui a ansiedade.', 'Pode dar sono. Cuidado para não cair. Não pare de uma vez.')),
 ('ANTIPSICÓTICOS', 'N5P', ('remédio para a mente', 'Trata problemas da mente e do comportamento.', 'Não pare de uma vez. Pode dar sono.')),
 ('PSICOESTIMULANTES', 'N6E', ('remédio para atenção', 'Ajuda na atenção e na concentração.', '')),
 ('ANTIALZHEIMER', 'N7A', ('remédio para memória', 'Usado no Alzheimer para ajudar a memória.', 'Tome sempre no mesmo horário.')),
 ('ANTIVERTIGINOSOS', 'N7V', ('remédio para tontura', 'Alivia tontura e labirintite.', 'Pode dar sono.')),
 ('LÁGRIMAS ARTIFICIAIS', 'S1L', ('colírio lubrificante', 'Alivia olho seco.', 'Use só nos olhos.')),
 ('ANTIGLAUCOMA', 'S1G', ('colírio para glaucoma', 'Controla a pressão do olho, no glaucoma.', 'Use todos os dias, no horário certo.')),
 ('DISFUNÇÃO ERÉTIL', 'G4E', ('remédio para ereção', 'Usado na disfunção erétil.', 'Não use junto com remédio de nitrato para o coração.')),
 ('CONTRACEPTIV', 'G3C', ('anticoncepcional', 'Evita a gravidez.', 'Tome sempre no mesmo horário.')),
 ('PREPARAÇÕES ANTITIREOIDE', 'H3A', ('remédio da tireoide', 'Diminui o excesso de hormônio da tireoide.', '')),
 ('PREPARAÇÕES PARA TIREOIDE', 'H3T', ('remédio da tireoide', 'Repõe o hormônio da tireoide.', 'Costuma ser tomado em jejum, de manhã.')),
 ('VITAMINA D', 'A11D', ('vitamina D', 'Repõe vitamina D e ajuda os ossos.', '')),
 ('FERRO PURO', 'B3F', ('remédio de ferro', 'Repõe ferro e trata a anemia.', 'Pode escurecer as fezes. Isso é normal.')),
 ('DIURÉTICOS DE ALÇA', 'C3A', ('remédio que faz urinar', 'Tira o excesso de água do corpo e diminui o inchaço.', 'Faz ir muitas vezes ao banheiro. Costuma ser tomado de manhã.')),
 ('INIBIDORES DA AGRAGAÇÃO', 'B1P', ('remédio para afinar o sangue', 'Ajuda a evitar infarto e derrame.', 'Pode causar sangramento. Avise o dentista e o médico que você toma.')),
 ('INIBIDORES DA AGREGAÇÃO', 'B1P', ('remédio para afinar o sangue', 'Ajuda a evitar infarto e derrame.', 'Pode causar sangramento. Avise o dentista e o médico que você toma.')),
 ('INSULINA', 'A10I', ('insulina', 'Controla o açúcar no sangue, no diabetes.', 'Guarde na geladeira. Se sentir tremor ou suor frio, coma algo doce.')),
 ('ASSOCIAÇÕES DE FERRO', 'B3F', ('remédio de ferro', 'Repõe ferro e trata a anemia.', 'Pode escurecer as fezes. Isso é normal.')),
]
